#-------------------------------
# General Site Settings
baseURL = "https://www.14thbelow.com"
languageCode = "en-us"
title = "14thBelow.com"
googleAnalytics = "G-VDB1FEM1FH" # Add your identifier. 
paginate = 9

[backend]
name = "git-gateway"
branch = "main"

[[collections]]
name = "blog"
label = "Blog"
folder = "content/blog"
create = true
slug = "{{year}}-{{month}}-{{day}}-{{slug}}"

  [collections.editor]
  preview = true

  [[collections.fields]]
  label = "Title"
  name = "title"
  widget = "string"

  [[collections.fields]]
  label = "Publish Date"
  name = "date"
  widget = "datetime"

  [[collections.fields]]
  label = "Description"
  name = "description"
  widget = "string"

  [[collections.fields]]
  label = "Body"
  name = "body"
  widget = "markdown"

 [[collections.fields]]
  label = "Images"
  name = "images"
  widget = "markdown"




#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 2


  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 3

[params]
  logo = "/images/14th.png" 
  description = "The NYC Art Blog. New Listings Every Week!"

  #-------------------------------
  # Author Settings
  [params.author]
    author__name = ""
    author__image = "/images/14th225.png"
    author__avatar = "/images/14th225.png"
    author__description = "NYC's Art & Culture Blog"

 [[params.social]]
    icon = "ion-logo-instagram"
    name = "Instagram"
    link = "https://www.instagram.com/14thbelow"

  # Example of adding a new link to the author section and footer:
  # [[params.social]]
  #   icon = "ion-logo-vimeo"
  #   name = "Vimeo"
  #   link = "https://vimeo.com"

  # Other icons can be found at https://ionicons.com/v4/


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false